/**
 * Keccak-f[1600], the Keccak sponge, Keccak-256 (original padding, as used by
 * Ethereum) and SHA3-256 (FIPS 202 padding).
 *
 * Vectors:
 *   - Every step of every round of Keccak-f[1600]: the Keccak team,
 *     "KeccakF-1600-IntermediateValues.txt", eXtended Keccak Code Package
 *     (https://raw.githubusercontent.com/XKCP/XKCP/master/tests/TestVectors/KeccakF-1600-IntermediateValues.txt),
 *     stored unmodified in test/fixtures/keccakf1600-intermediate-values.txt.
 *     It also lists the round constants and the rho offsets.
 *   - Keccak-256 with the original pad10*1 rule: the Keccak team, round-3
 *     submission KAT "ShortMsgKAT_256.txt" (https://keccak.team/obsolete/KeccakKAT-3.zip);
 *     its 256 byte-aligned entries (0 to 255 bytes, so the lengths 135, 136 and
 *     137 around the 136-byte rate are included) are stored in
 *     test/fixtures/keccak256-shortmsgkat.json.
 *   - Keccak-256 of the empty string: EIP-1052, "EXTCODEHASH opcode"
 *     (https://eips.ethereum.org/EIPS/eip-1052).
 *   - SHA3-256 of the empty string: XKCP "ShortMsgKAT_SHA3-256.txt"
 *     (https://raw.githubusercontent.com/XKCP/XKCP/master/tests/TestVectors/ShortMsgKAT_SHA3-256.txt),
 *     and node:crypto ('sha3-256', 'sha3-512', 'shake256') on seeded random inputs.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import {
  KECCAK_STEPS,
  ROUND_CONSTANTS,
  RHO_OFFSETS,
  createState,
  getLane,
  setLane,
  stateToBytes,
  bytesToState,
  stateToBits,
  bitsToState,
  keccakStep,
  keccakRound,
  keccakF1600,
  keccakSponge,
  keccak256,
  keccak256Hex,
  sha3_256,
  sha3_256Hex,
} from '../src/lib/keccak.js';
import { bytesToHex, hexToBytes, utf8Bytes } from '../src/lib/bytes.js';
import { createRandom } from '../src/lib/random.js';

const fixture = (name) => readFileSync(new URL(`./fixtures/${name}`, import.meta.url), 'utf8');

/* ------------------------------------------------------------------------ */
/* Parsing the intermediate-values file                                     */
/* ------------------------------------------------------------------------ */

function parseIntermediateValues(text) {
  const lines = text.replace(/\r/g, '').split('\n');
  const rc = [];
  const rho = {};
  const examples = [];
  let current = null;
  let round = -1;
  const lanesAt = (i) => {
    const rows = lines.slice(i, i + 5).map((l) => l.trim().split(/\s+/).map((h) => BigInt(`0x${h}`)));
    return rows; // rows[y][x]
  };
  const bytesAt = (i) => hexToBytes(lines[i].trim().split(/\s+/).join(''));
  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i];
    let m;
    if ((m = line.match(/^RC\[(\d+)\]\[0\]\[0\] = ([0-9A-F]{16})$/))) rc[Number(m[1])] = BigInt(`0x${m[2]}`);
    else if ((m = line.match(/^RhoOffset\[(\d)\]\[(\d)\] = +(\d+)$/))) rho[`${m[1]},${m[2]}`] = Number(m[3]);
    else if (line.startsWith('+++ Example')) {
      current = { rounds: [] };
      examples.push(current);
    } else if (line === 'Input of permutation:') current.input = bytesAt(i + 1);
    else if (line === 'Same, with lanes as 64-bit words:') current.inputLanes = lanesAt(i + 1);
    else if ((m = line.match(/^--- Round (\d+) ---$/))) {
      round = Number(m[1]);
      current.rounds[round] = {};
    } else if ((m = line.match(/^After (theta|rho|pi|chi|iota):$/))) current.rounds[round][m[1]] = lanesAt(i + 1);
    else if (line === 'State after permutation:') current.output = bytesAt(i + 1);
  }
  return { rc, rho, examples };
}

const IV = parseIntermediateValues(fixture('keccakf1600-intermediate-values.txt'));

function assertLanes(state, rows, label) {
  for (let y = 0; y < 5; y += 1) {
    for (let x = 0; x < 5; x += 1) {
      assert.equal(getLane(state, x, y), rows[y][x], `${label}: lane (${x}, ${y})`);
    }
  }
}

/* ------------------------------------------------------------------------ */
/* The permutation                                                           */
/* ------------------------------------------------------------------------ */

test('the intermediate-values file parsed into two examples of 24 rounds', () => {
  assert.equal(IV.rc.length, 24);
  assert.equal(Object.keys(IV.rho).length, 25);
  assert.equal(IV.examples.length, 2);
  for (const ex of IV.examples) {
    assert.equal(ex.rounds.length, 24);
    assert.equal(ex.input.length, 200);
    assert.equal(ex.output.length, 200);
  }
});

test('round constants generated by the LFSR of FIPS 202 match the Keccak team list', () => {
  assert.deepEqual([...ROUND_CONSTANTS], IV.rc);
});

test('rho offsets generated by FIPS 202 Algorithm 2 match the Keccak team list', () => {
  for (let x = 0; x < 5; x += 1) {
    for (let y = 0; y < 5; y += 1) assert.equal(RHO_OFFSETS[x + 5 * y], IV.rho[`${x},${y}`], `(${x}, ${y})`);
  }
});

test('bytesToState reads lanes as little-endian 64-bit words (lane (x, y) at bytes 8(x + 5y))', () => {
  for (const ex of IV.examples) assertLanes(bytesToState(ex.input), ex.inputLanes, 'input');
  const state = bytesToState(IV.examples[1].input);
  assert.equal(bytesToHex(stateToBytes(state)), bytesToHex(IV.examples[1].input));
});

test('keccakStep reproduces every step of every round of both examples', () => {
  assert.deepEqual(KECCAK_STEPS, ['theta', 'rho', 'pi', 'chi', 'iota']);
  for (const [e, ex] of IV.examples.entries()) {
    const state = bytesToState(ex.input);
    for (let r = 0; r < 24; r += 1) {
      for (const step of KECCAK_STEPS) {
        keccakStep(state, step, r);
        assertLanes(state, ex.rounds[r][step], `example ${e}, round ${r}, after ${step}`);
      }
    }
    assert.equal(bytesToHex(stateToBytes(state)), bytesToHex(ex.output));
  }
});

test('keccakRound composes the five steps; keccakF1600 composes the 24 rounds', () => {
  for (const ex of IV.examples) {
    const byRounds = bytesToState(ex.input);
    for (let r = 0; r < 24; r += 1) {
      keccakRound(byRounds, r);
      assertLanes(byRounds, ex.rounds[r].iota, `round ${r}`);
    }
    const whole = bytesToState(ex.input);
    assert.equal(keccakF1600(whole), whole, 'permutes in place and returns the state');
    assert.equal(bytesToHex(stateToBytes(whole)), bytesToHex(ex.output));
  }
});

test('keccakStep rejects unknown steps and round indices', () => {
  assert.throws(() => keccakStep(createState(), 'omega', 0), /step/);
  assert.throws(() => keccakStep(createState(), 'iota', 24), /round/);
  assert.throws(() => keccakRound(createState(), -1), /round/);
});

test('stateToBits indexes bit z of lane (x, y) as 64(x + 5y) + z and round-trips', () => {
  const state = createState();
  assert.equal(state.length, 50);
  setLane(state, 3, 2, (1n << 63n) | 5n);
  const bits = stateToBits(state);
  assert.equal(bits.length, 1600);
  const base = 64 * (3 + 5 * 2);
  assert.deepEqual([bits[base], bits[base + 1], bits[base + 2], bits[base + 63]], [1, 0, 1, 1]);
  assert.equal(bits.reduce((s, b) => s + b, 0), 3);

  const random = bytesToState(createRandom(1600).bytes(200));
  const back = bitsToState(stateToBits(random));
  assert.deepEqual([...back], [...random]);
  // The same ordering as FIPS 202: bit 8k + j of the byte string is bit j of byte k.
  const bytes = stateToBytes(random);
  const fromBits = stateToBits(random);
  for (const i of [0, 7, 8, 63, 64, 999, 1599]) assert.equal(fromBits[i], (bytes[i >> 3] >> (i & 7)) & 1);
});

/* ------------------------------------------------------------------------ */
/* Keccak-256 and SHA3-256                                                   */
/* ------------------------------------------------------------------------ */

test('keccak256 of the empty string (EIP-1052)', () => {
  assert.equal(keccak256Hex(new Uint8Array(0)), 'c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470');
  assert.equal(keccak256(new Uint8Array(0)).length, 32);
});

test('keccak256 matches the 256 byte-aligned entries of the Keccak team ShortMsgKAT_256', () => {
  const kat = JSON.parse(fixture('keccak256-shortmsgkat.json'));
  assert.equal(kat.length, 256);
  for (const { bytes, msg, md } of kat) {
    const message = hexToBytes(msg);
    assert.equal(message.length, bytes);
    assert.equal(keccak256Hex(message), md, `${bytes} bytes`);
  }
  for (const n of [135, 136, 137]) assert.ok(kat.some((e) => e.bytes === n), `length ${n} covered`);
});

test('sha3_256 of the empty string (XKCP ShortMsgKAT_SHA3-256, Len = 0)', () => {
  assert.equal(sha3_256Hex(new Uint8Array(0)), 'a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a');
});

test('sha3_256 agrees with node:crypto, including the 135/136/137-byte rate boundary and multi-block inputs', () => {
  const rnd = createRandom(202);
  for (const length of [0, 1, 3, 71, 72, 73, 134, 135, 136, 137, 271, 272, 273, 1000, 5000]) {
    const message = rnd.bytes(length);
    assert.equal(sha3_256Hex(message), createHash('sha3-256').update(message).digest('hex'), `length ${length}`);
  }
  assert.equal(sha3_256Hex(utf8Bytes('abc')), createHash('sha3-256').update('abc').digest('hex'));
  assert.equal(sha3_256(new Uint8Array(0)).length, 32);
});

test('Keccak-256 and SHA3-256 differ only by the domain-separation suffix', () => {
  const message = utf8Bytes('abc');
  assert.notEqual(keccak256Hex(message), sha3_256Hex(message));
  assert.equal(bytesToHex(keccakSponge(136, 0x01, message, 32)), keccak256Hex(message));
  assert.equal(bytesToHex(keccakSponge(136, 0x06, message, 32)), sha3_256Hex(message));
});

test('keccakSponge with other parameters: SHA3-512 (rate 72) and SHAKE256 squeezing several blocks', () => {
  const rnd = createRandom(1088);
  for (const length of [0, 71, 72, 73, 500]) {
    const message = rnd.bytes(length);
    assert.equal(
      bytesToHex(keccakSponge(72, 0x06, message, 64)),
      createHash('sha3-512').update(message).digest('hex'),
      `sha3-512, length ${length}`,
    );
    assert.equal(
      bytesToHex(keccakSponge(136, 0x1f, message, 300)),
      createHash('shake256', { outputLength: 300 }).update(message).digest('hex'),
      `shake256, length ${length}`,
    );
  }
});

test('keccakSponge rejects invalid rates and suffixes', () => {
  assert.throws(() => keccakSponge(0, 0x01, new Uint8Array(0), 32), /rate/);
  assert.throws(() => keccakSponge(201, 0x01, new Uint8Array(0), 32), /rate/);
  assert.throws(() => keccakSponge(136, 0x00, new Uint8Array(0), 32), /suffix/);
});
